# Generated by Django 4.0.8 on 2022-10-10 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('qualification', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=70)),
                ('description', models.TextField()),
            ],
        ),
    ]
